site_name: Laravel Translated Routes
site_url: https://translated-routes.com
repo_url: https://github.com/abdoulhaqjr/laravel-translated-routes
theme:
  name: material
  language: fr
nav:
  - Accueil: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Utilisation: utilisation.md
  - Middleware: middleware.md
  - Tests: tests.md
  - Licence: licence.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abdoulhaqjr/laravel-translated-routes